### ISSUE TITLE
Broken for KDE 5

### ISSUE THREAD

**Issue by c-c-6ypo8** [alvatip/Borealis-cursors#1]
Cannot install on KDE 5 without `cursor.theme` file inside the tar.gz archive. I've created it by myself with this content and installation completed successfully:

```config
[Icon Theme]
Name="Borealis-cursors"
```

**Comment by alvatip** [comment]
Thank for letting me know, 
I will check it and add the cursor.theme file inside tar.gz, this is most likely an omission on my side

**Comment by github12101** [comment]
Confirming. Cursor set cannot be installed from KDE store page.
![image](https://github.com/alvatip/Borealis-cursors/assets/1646393/9518eb4a-1504-4d3c-9d47-2e510a1322a5)

**Comment by alvatip** [comment]
@github12101,
Your issue is not related,
When prompted to select a file (see below):
![image](https://github.com/alvatip/Borealis-cursors/assets/84344248/d7506e27-a407-4b00-9968-5c958518e8ba)
As it is linked to Pling.com, all files are presented, for linux you should select .tar.gz -> the 4th one
If you select the first one, this is a link to a web page, hence the error message (xxxxx "because it points to a web page." xxxx)

**Comment by alvatip** [comment]
@c-c-6ypo8, 
.tar.gz file was for some reason not well created (kind of strange but whatever)
I will update it on Pling.com -> should work fine when trying to install from within settings - "Get new cursors" (not tried yet)
and also when using the option - "Install from files" (tried and working fine) 

Edit: Tried both way and they worked without any issue with new file I just uploaded
